import { normalizeManifest } from "./config.js";
import { SecurityError } from "./security.js";

const ACCOUNT_PATTERN = /^[a-z_][a-z0-9_-]{0,30}$/u;
const PUBLIC_KEY_PATTERN = /^(?:ssh-ed25519|sk-ssh-ed25519@openssh\.com) [A-Za-z0-9+/]+={0,3}(?: [^\r\n]{1,128})?$/u;

function accountName(value, label) {
  if (typeof value !== "string" || !ACCOUNT_PATTERN.test(value)) {
    throw new SecurityError(`${label} is not a safe system account name`);
  }
  return value;
}

function exactIpv4ListenerFromUrl(value, label) {
  const parsed = new URL(value);
  if (parsed.protocol !== "http:" || parsed.hostname !== "127.0.0.1" || !parsed.port) {
    throw new SecurityError(`${label} must use exact loopback 127.0.0.1`);
  }
  return `127.0.0.1:${Number(parsed.port)}`;
}

function exactIpv4Listener(value, label) {
  const match = /^127\.0\.0\.1:([1-9][0-9]{0,4})$/u.exec(value);
  const port = match === null ? 0 : Number(match[1]);
  if (port < 1 || port > 65535) {
    throw new SecurityError(`${label} must use exact loopback 127.0.0.1`);
  }
  return value;
}

function tunnelListeners(input) {
  const manifest = normalizeManifest(input);
  const listeners = manifest.spec.services.map((service) => (
    exactIpv4ListenerFromUrl(service.edge.upstream, `${service.id}.edge.upstream`)
  ));
  return [...new Set(listeners)].sort((left, right) => {
    const leftPort = Number(left.slice(left.lastIndexOf(":") + 1));
    const rightPort = Number(right.slice(right.lastIndexOf(":") + 1));
    return leftPort - rightPort;
  });
}

function normalizePublicKey(value) {
  if (typeof value !== "string") {
    throw new SecurityError("A dedicated OpenSSH public key is required");
  }
  const key = value.trim();
  if (!PUBLIC_KEY_PATTERN.test(key)) {
    throw new SecurityError("Tunnel public key must be an Ed25519 OpenSSH public key");
  }
  return key;
}

export function renderTunnelAuthorizedKey(input, publicKey, {
  comment = "lazyedge outbound reverse tunnel",
} = {}) {
  const listeners = tunnelListeners(input);
  const key = normalizePublicKey(publicKey);
  if (typeof comment !== "string" || !/^[A-Za-z0-9 ._@+-]{1,128}$/u.test(comment)) {
    throw new SecurityError("authorized_keys comment is invalid");
  }
  const keyParts = key.split(" ");
  const normalizedKey = `${keyParts[0]} ${keyParts[1]}`;
  const permissions = listeners.map((listener) => `permitlisten="${listener}"`);
  const options = ["restrict", "port-forwarding", ...permissions].join(",");
  return `${options} ${normalizedKey} ${comment}\n`;
}

export function renderTunnelSshdConfig(input, {
  tunnelUser,
} = {}) {
  const manifest = normalizeManifest(input);
  const user = accountName(
    tunnelUser ?? manifest.spec.transport.sshUser ?? "lazyedge-tunnel",
    "tunnelUser",
  );
  const listeners = tunnelListeners(manifest);
  return [
    "# Generated by LazyEdge. Keep this Match block in a dedicated include file.",
    `Match User ${user}`,
    "    AuthenticationMethods publickey",
    "    PubkeyAuthentication yes",
    "    PasswordAuthentication no",
    "    KbdInteractiveAuthentication no",
    "    AllowTcpForwarding remote",
    "    AllowStreamLocalForwarding no",
    "    GatewayPorts no",
    `    PermitListen ${listeners.join(" ")}`,
    "    PermitOpen none",
    "    AllowAgentForwarding no",
    "    X11Forwarding no",
    "    PermitTTY no",
    "    PermitTunnel no",
    "    MaxSessions 0",
    "Match all",
    "",
  ].join("\n");
}

function shellLiteral(value) {
  if (typeof value !== "string" || /[\u0000\r\n]/u.test(value)) {
    throw new SecurityError("Unsafe value in bootstrap renderer");
  }
  return `'${value.replaceAll("'", `'"'"'`)}'`;
}

export function renderBootstrapScript(input, {
  publicKey,
  serviceUser = "lazyedge",
  tunnelUser,
  certificateGroup = "certread",
  sshdInclude = "/etc/ssh/sshd_config.d/60-lazyedge-tunnel.conf",
} = {}) {
  const manifest = normalizeManifest(input);
  const edgeUser = accountName(serviceUser, "serviceUser");
  const sshUser = accountName(
    tunnelUser ?? manifest.spec.transport.sshUser ?? "lazyedge-tunnel",
    "tunnelUser",
  );
  const certGroup = accountName(certificateGroup, "certificateGroup");
  if (edgeUser === sshUser) {
    throw new SecurityError("Edge and tunnel accounts must be separate");
  }
  if (sshdInclude !== "/etc/ssh/sshd_config.d/60-lazyedge-tunnel.conf") {
    throw new SecurityError("sshdInclude must use LazyEdge's dedicated include path");
  }
  const authorizedKey = renderTunnelAuthorizedKey(manifest, publicKey);
  const sshdConfig = renderTunnelSshdConfig(manifest, { tunnelUser: sshUser });
  const edgeHome = `/var/lib/${edgeUser}`;
  const tunnelHome = `/var/lib/${sshUser}`;

  return `#!/usr/bin/env bash
set -euo pipefail
umask 077

test "$(id -u)" -eq 0 || { echo "LazyEdge bootstrap must run as root" >&2; exit 2; }
command -v useradd >/dev/null
command -v groupadd >/dev/null
command -v sshd >/dev/null

getent group ${shellLiteral(certGroup)} >/dev/null || groupadd --system ${shellLiteral(certGroup)}

ensure_system_user() {
  local user=$1 home=$2
  if getent passwd "$user" >/dev/null; then
    test "$(getent passwd "$user" | cut -d: -f6)" = "$home"
    test "$(getent passwd "$user" | cut -d: -f7)" = "/usr/sbin/nologin"
  else
    useradd --system --user-group --create-home --home-dir "$home" --shell /usr/sbin/nologin "$user"
  fi
}

ensure_system_user ${shellLiteral(edgeUser)} ${shellLiteral(edgeHome)}
ensure_system_user ${shellLiteral(sshUser)} ${shellLiteral(tunnelHome)}

install -d -o root -g root -m 0755 /opt/lazyedge /opt/lazyedge/releases
install -d -o root -g root -m 0755 /etc/lazyedge
install -d -o ${shellLiteral(edgeUser)} -g ${shellLiteral(edgeUser)} -m 0750 /var/lib/lazyedge /var/log/lazyedge
install -d -o ${shellLiteral(sshUser)} -g ${shellLiteral(sshUser)} -m 0700 ${shellLiteral(`${tunnelHome}/.ssh`)}

stage=$(mktemp -d /run/lazyedge-bootstrap.XXXXXX)
candidate=""
authorized_candidate=""
committed=0
had_previous=0
authorized_changed=0
had_previous_authorized=0
authorized_path=${shellLiteral(`${tunnelHome}/.ssh/authorized_keys`)}
cleanup() {
  status=$?
  trap - EXIT HUP INT TERM
  if test "$committed" -ne 1; then
    if test "$had_previous" -eq 1; then
      restore=$(mktemp /etc/ssh/sshd_config.d/.lazyedge-sshd-restore.XXXXXX)
      cp --preserve=mode,ownership "$stage/sshd.previous" "$restore"
      mv -f "$restore" ${shellLiteral(sshdInclude)}
    else
      rm -f ${shellLiteral(sshdInclude)}
    fi
    if sshd -t; then systemctl reload ssh.service || true; fi
  fi
  if test "$committed" -ne 1 && test "$authorized_changed" -eq 1; then
    if test "$had_previous_authorized" -eq 1; then
      authorized_restore=$(mktemp ${shellLiteral(`${tunnelHome}/.ssh/.authorized_keys-restore.XXXXXX`)})
      cp --preserve=mode,ownership "$stage/authorized_keys.previous" "$authorized_restore"
      mv -f "$authorized_restore" "$authorized_path"
    else
      rm -f "$authorized_path"
    fi
  fi
  rm -f "$stage/authorized_keys" "$stage/sshd.conf" "$stage/sshd.previous" \
    "$stage/authorized_keys.previous" "$candidate" "$authorized_candidate"
  rmdir "$stage" 2>/dev/null || true
  exit "$status"
}
trap cleanup EXIT
trap 'exit 130' HUP INT TERM

cat >"$stage/authorized_keys" <<'LAZYEDGE_AUTHORIZED_KEYS'
${authorizedKey}LAZYEDGE_AUTHORIZED_KEYS
cat >"$stage/sshd.conf" <<'LAZYEDGE_SSHD_CONFIG'
${sshdConfig}LAZYEDGE_SSHD_CONFIG

test ! -L "$authorized_path" || {
  echo "Refusing a symlinked authorized_keys file" >&2
  exit 3
}
if test -e "$authorized_path"; then
  cp --preserve=mode,ownership "$authorized_path" "$stage/authorized_keys.previous"
  had_previous_authorized=1
fi
authorized_candidate=$(mktemp ${shellLiteral(`${tunnelHome}/.ssh/.authorized_keys-candidate.XXXXXX`)})
install -o ${shellLiteral(sshUser)} -g ${shellLiteral(sshUser)} -m 0600 \
  "$stage/authorized_keys" "$authorized_candidate"
mv -f "$authorized_candidate" "$authorized_path"
authorized_candidate=""
authorized_changed=1

test ! -L ${shellLiteral(sshdInclude)} || {
  echo "Refusing a symlinked sshd include" >&2
  exit 3
}
if test -e ${shellLiteral(sshdInclude)}; then
  cp --preserve=mode,ownership ${shellLiteral(sshdInclude)} "$stage/sshd.previous"
  had_previous=1
fi
candidate=$(mktemp /etc/ssh/sshd_config.d/.lazyedge-sshd-candidate.XXXXXX)
install -o root -g root -m 0644 "$stage/sshd.conf" "$candidate"
mv -f "$candidate" ${shellLiteral(sshdInclude)}
candidate=""

sshd -t
systemctl reload ssh.service
committed=1
echo "LazyEdge accounts and restricted tunnel identity are ready."
`;
}

export function renderServiceAccountBootstrap(input, options = {}) {
  return renderBootstrapScript(input, options);
}

export function assertExactTunnelListeners(input) {
  return tunnelListeners(input).map((listener) => exactIpv4Listener(listener, "PermitListen"));
}
