import { normalizeManifest } from "./config.js";
import { normalizeLoopbackListener, SecurityError } from "./security.js";

export { renderTunnelAuthorizedKey } from "./accounts.js";

const SSH_ALIAS_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]{0,62}$/u;
const ABSOLUTE_PATH_PATTERN = /^\/(?:[A-Za-z0-9._@+-]+\/)*[A-Za-z0-9._@+-]+$/u;

function safePath(value, label) {
  if (typeof value !== "string" || !ABSOLUTE_PATH_PATTERN.test(value) || value.includes("..")) {
    throw new SecurityError(`${label} must be a simple absolute path`);
  }
  return value;
}

function exactIpv4Listener(value, label) {
  const listener = normalizeLoopbackListener(value, label);
  if (listener.host !== "127.0.0.1") {
    throw new SecurityError(`${label} must use exact loopback 127.0.0.1`);
  }
  return listener.value;
}

function upstreamListener(value, label) {
  const parsed = new URL(value);
  if (parsed.protocol !== "http:" || parsed.hostname !== "127.0.0.1" || !parsed.port) {
    throw new SecurityError(`${label} must be http://127.0.0.1:<port>`);
  }
  return `127.0.0.1:${Number(parsed.port)}`;
}

export function openSshForwards(input) {
  const manifest = normalizeManifest(input);
  return Object.freeze(manifest.spec.services.map((service) => Object.freeze({
    service: service.id,
    remote: upstreamListener(service.edge.upstream, `${service.id}.edge.upstream`),
    local: exactIpv4Listener(service.worker.listen, `${service.id}.worker.listen`),
  })).sort((left, right) => left.remote.localeCompare(right.remote)));
}

export function renderOpenSshConfig(input, {
  alias = "lazyedge-edge",
  identityFile = "/home/lazyedge/.config/lazyedge/ssh/id_ed25519",
  knownHostsFile = "/home/lazyedge/.config/lazyedge/ssh/known_hosts",
  serverAliveInterval = 15,
  serverAliveCountMax = 3,
} = {}) {
  const manifest = normalizeManifest(input);
  const transport = manifest.spec.transport;
  if (!SSH_ALIAS_PATTERN.test(alias)) throw new SecurityError("SSH alias is invalid");
  if (typeof transport.sshHost !== "string" || typeof transport.sshUser !== "string") {
    throw new SecurityError("transport.sshHost and transport.sshUser are required for OpenSSH");
  }
  if (
    !Number.isInteger(serverAliveInterval)
    || serverAliveInterval < 5
    || serverAliveInterval > 300
    || !Number.isInteger(serverAliveCountMax)
    || serverAliveCountMax < 1
    || serverAliveCountMax > 10
  ) {
    throw new SecurityError("OpenSSH keepalive settings are outside their safe range");
  }
  const identity = safePath(identityFile, "identityFile");
  const knownHosts = safePath(knownHostsFile, "knownHostsFile");
  const port = transport.sshPort ?? 22;
  const forwards = openSshForwards(manifest);

  const hostKeyAlias = transport.hostKeyAlias === undefined
    ? []
    : [`    HostKeyAlias ${transport.hostKeyAlias}`];

  return [
    "# Generated by LazyEdge. This is one connection for every approved reverse forward.",
    `Host ${alias}`,
    `    HostName ${transport.sshHost}`,
    `    User ${transport.sshUser}`,
    `    Port ${port}`,
    `    IdentityFile ${identity}`,
    "    IdentitiesOnly yes",
    `    UserKnownHostsFile ${knownHosts}`,
    ...hostKeyAlias,
    "    GlobalKnownHostsFile /dev/null",
    "    StrictHostKeyChecking yes",
    "    UpdateHostKeys no",
    "    VerifyHostKeyDNS no",
    "    CheckHostIP no",
    "    BatchMode yes",
    "    PreferredAuthentications publickey",
    "    PasswordAuthentication no",
    "    KbdInteractiveAuthentication no",
    "    ExitOnForwardFailure yes",
    `    ServerAliveInterval ${serverAliveInterval}`,
    `    ServerAliveCountMax ${serverAliveCountMax}`,
    "    TCPKeepAlive yes",
    "    ConnectTimeout 10",
    "    ConnectionAttempts 3",
    "    ClearAllForwardings no",
    "    ForwardAgent no",
    "    ForwardX11 no",
    "    RequestTTY no",
    "    SessionType none",
    "    StdinNull yes",
    "    ControlMaster no",
    ...forwards.map(({ remote, local }) => `    RemoteForward ${remote} ${local}`),
    "",
  ].join("\n");
}

export function renderPinnedKnownHosts(input, hostKey) {
  const manifest = normalizeManifest(input);
  const { sshHost, sshPort = 22, hostKeyAlias } = manifest.spec.transport;
  if (typeof sshHost !== "string") throw new SecurityError("transport.sshHost is required");
  if (
    typeof hostKey !== "string"
    || !/^(?:ssh-ed25519|sk-ssh-ed25519@openssh\.com) [A-Za-z0-9+/]+={0,3}$/u.test(hostKey)
  ) {
    throw new SecurityError("hostKey must be an out-of-band verified Ed25519 key");
  }
  const host = hostKeyAlias ?? (sshPort === 22 ? sshHost : `[${sshHost}]:${sshPort}`);
  return `${host} ${hostKey}\n`;
}

export function openSshCommand(input, {
  alias = "lazyedge-edge",
  configPath = "/home/lazyedge/.config/lazyedge/ssh/config",
} = {}) {
  normalizeManifest(input);
  if (!SSH_ALIAS_PATTERN.test(alias)) throw new SecurityError("SSH alias is invalid");
  const config = safePath(configPath, "configPath");
  return Object.freeze({
    file: "/usr/bin/ssh",
    args: Object.freeze(["-NT", "-F", config, alias]),
  });
}
